# Generated by Django 4.2.7 on 2023-11-25 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0003_paymentrecievedmodel_cheque_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecievedmodel',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.bankcreation'),
        ),
        migrations.AlterField(
            model_name='paymentrecievedmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
