# Generated by Django 4.2.7 on 2023-11-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0004_paymentrecievedmodel_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecievedmodel',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
