# Generated by Django 4.2.7 on 2023-11-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0010_rename_my_id_paymentrecievedidmodel_last_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecievedmodel',
            name='customer_gst_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
