# Generated by Django 4.2.7 on 2023-11-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0011_alter_paymentrecievedmodel_customer_gst_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecievedmodel',
            name='acc_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrecievedmodel',
            name='cheque_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrecievedmodel',
            name='upi_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
