# Generated by Django 4.2.7 on 2023-11-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0015_paymentrecievedmodel_paymentrecievedidmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecievedidmodel',
            name='pay_rec_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrecievedidmodel',
            name='ref_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
