# Generated by Django 4.2.7 on 2023-11-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0016_alter_paymentrecievedidmodel_pay_rec_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrecievedmodel',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='paymentrecievedmodel',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='paymentrecievedmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='PaymentRecievedIdModel',
        ),
        migrations.DeleteModel(
            name='PaymentRecievedModel',
        ),
    ]
