# Generated by Django 4.2.7 on 2023-11-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0023_alter_paymentrecievedmodel_customer_gst_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecievedmodel',
            name='customer_gst_treatment',
            field=models.CharField(blank=True, default='value', max_length=255),
        ),
    ]
