# Generated by Django 4.2.7 on 2023-11-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0024_alter_paymentrecievedmodel_customer_gst_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecievedmodel',
            name='pay_rec_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecievedmodel',
            name='pay_rec_balance',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecievedmodel',
            name='pay_rec_paid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
