# Generated by Django 4.2.7 on 2023-11-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0025_paymentrecievedmodel_pay_rec_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecievedmodel',
            name='pay_rec_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrecievedmodel',
            name='pay_rec_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrecievedmodel',
            name='pay_rec_paid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
