# Generated by Django 4.2.7 on 2023-11-30 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0026_alter_paymentrecievedmodel_pay_rec_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecievedAllInvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('due_date', models.DateField(null=True)),
                ('invoice_type', models.CharField(max_length=255, null=True)),
                ('invoice', models.CharField(max_length=255, null=True)),
                ('invoice_amount', models.FloatField(blank=True, null=True)),
                ('paid', models.FloatField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='paymentrecievedmodel',
            name='all_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.paymentrecievedallinvoices'),
        ),
    ]
