# Generated by Django 4.2.7 on 2023-11-30 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0028_rename_invoice_paymentrecievedallinvoices_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrecievedmodel',
            name='all_invoice',
        ),
        migrations.AddField(
            model_name='paymentrecievedallinvoices',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.customer'),
        ),
        migrations.AddField(
            model_name='paymentrecievedallinvoices',
            name='payment_recieved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.paymentrecievedmodel'),
        ),
        migrations.AddField(
            model_name='paymentrecievedallinvoices',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
