# Generated by Django 4.2.7 on 2023-11-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0029_remove_paymentrecievedmodel_all_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='balance',
            field=models.FloatField(default=0, null=True),
        ),
    ]
