# Generated by Django 4.2.7 on 2023-12-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0031_paymentrecievedcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecievedcomments',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
