# Generated by Django 4.2.7 on 2023-12-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0032_paymentrecievedcomments_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecievedcomments',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
