# Generated by Django 4.2.7 on 2023-12-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0033_paymentrecievedcomments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecievedcomments',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
