# Generated by Django 4.2.7 on 2023-12-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0034_alter_paymentrecievedcomments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecievedmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
