# Generated by Django 4.2.7 on 2023-12-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0035_paymentrecievedmodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecievedmodel',
            name='file_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
