# Generated by Django 4.2.7 on 2023-12-02 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0037_ewaybillidmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ewaybillitem',
            name='eway_bill',
        ),
        migrations.DeleteModel(
            name='EWayBill',
        ),
        migrations.DeleteModel(
            name='EWayBillItem',
        ),
    ]
