# Generated by Django 4.2.7 on 2023-12-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0039_ewaybill_ewaybillitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrecievedcomments',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='paymentrecievedcomments',
            name='payment_recieved',
        ),
        migrations.RemoveField(
            model_name='paymentrecievedcomments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentrecievedidmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentrecievedmodel',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='paymentrecievedmodel',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='paymentrecievedmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='PaymentRecievedAllInvoices',
        ),
        migrations.DeleteModel(
            name='PaymentREcievedComments',
        ),
        migrations.DeleteModel(
            name='PaymentRecievedIdModel',
        ),
        migrations.DeleteModel(
            name='PaymentRecievedModel',
        ),
    ]
