# Generated by Django 4.2.7 on 2023-12-02 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0040_remove_paymentrecievedcomments_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecievedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_mail', models.EmailField(max_length=254, null=True)),
                ('customer_bill_address', models.TextField()),
                ('customer_gst_treatment', models.CharField(blank=True, default='value', max_length=255)),
                ('customer_gst_number', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_recieved_number', models.CharField(max_length=255)),
                ('reference_number', models.CharField(max_length=255)),
                ('payment_recieved_date', models.DateTimeField(null=True)),
                ('payment_recieved_method', models.CharField(max_length=255)),
                ('cheque_id', models.CharField(blank=True, max_length=255, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('acc_num', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('pay_rec_amount', models.FloatField(blank=True, null=True)),
                ('pay_rec_paid', models.FloatField(blank=True, null=True)),
                ('pay_rec_balance', models.FloatField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='upload/')),
                ('file_comment', models.TextField(blank=True, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.bankcreation')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecievedIdModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(max_length=255, null=True)),
                ('pay_rec_number', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecievedComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.customer')),
                ('payment_recieved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.paymentrecievedmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecievedAllInvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('due_date', models.DateField(null=True)),
                ('invoice_type', models.CharField(max_length=255, null=True)),
                ('invoice_number', models.CharField(max_length=255, null=True)),
                ('invoice_amount', models.FloatField(blank=True, null=True)),
                ('paid', models.FloatField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.customer')),
                ('payment_recieved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.paymentrecievedmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
