# Generated by Django 4.2.7 on 2023-12-02 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0041_paymentrecievedmodel_paymentrecievedidmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ewaybillidmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ewaybillitem',
            name='eway_bill',
        ),
        migrations.DeleteModel(
            name='EWayBill',
        ),
        migrations.DeleteModel(
            name='EwaybillIdModel',
        ),
        migrations.DeleteModel(
            name='EWayBillItem',
        ),
    ]
