# Generated by Django 4.2.7 on 2023-12-02 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0042_remove_ewaybillidmodel_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EWayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.CharField(blank=True, max_length=50, null=True)),
                ('transsub', models.CharField(blank=True, max_length=50, null=True)),
                ('customerzz', models.CharField(blank=True, max_length=100, null=True)),
                ('cemail', models.EmailField(blank=True, max_length=255, null=True)),
                ('cgst_trt_inp', models.CharField(blank=True, max_length=100, null=True)),
                ('cgstin_inp', models.CharField(blank=True, max_length=100, null=True)),
                ('invoiceno', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('trans', models.CharField(blank=True, max_length=100, null=True)),
                ('adda', models.TextField(blank=True, max_length=255, null=True)),
                ('addb', models.TextField(blank=True, max_length=255, null=True)),
                ('srcofsupply', models.CharField(blank=True, max_length=100, null=True)),
                ('transportation', models.CharField(blank=True, max_length=100, null=True)),
                ('km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vno', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipping_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adj', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('cust', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EWayBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('eway_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zohoapp.ewaybill')),
            ],
        ),
        migrations.CreateModel(
            name='EwaybillIdModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(max_length=255, null=True)),
                ('eway_bill_number', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
