# Generated by Django 4.2.7 on 2023-12-03 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0043_ewaybill_ewaybillitem_ewaybillidmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ewaybillidmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ewaybillitem',
            name='eway_bill',
        ),
        migrations.RemoveField(
            model_name='paymentrecievedallinvoices',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='paymentrecievedallinvoices',
            name='payment_recieved',
        ),
        migrations.RemoveField(
            model_name='paymentrecievedallinvoices',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentrecievedcomments',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='paymentrecievedcomments',
            name='payment_recieved',
        ),
        migrations.RemoveField(
            model_name='paymentrecievedcomments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentrecievedidmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentrecievedmodel',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='paymentrecievedmodel',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='paymentrecievedmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='EWayBill',
        ),
        migrations.DeleteModel(
            name='EwaybillIdModel',
        ),
        migrations.DeleteModel(
            name='EWayBillItem',
        ),
        migrations.DeleteModel(
            name='PaymentRecievedAllInvoices',
        ),
        migrations.DeleteModel(
            name='PaymentRecievedComments',
        ),
        migrations.DeleteModel(
            name='PaymentRecievedIdModel',
        ),
        migrations.DeleteModel(
            name='PaymentRecievedModel',
        ),
    ]
