# Generated by Django 4.2.7 on 2023-12-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0046_transportation_type_transportation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewaybillitem',
            name='hsn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
