# Generated by Django 4.2.7 on 2023-12-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0049_ewaybillidmodel_pattern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecievedallinvoices',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
