# Generated by Django 4.2.7 on 2023-12-08 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0051_paymentrecievedmodel_pdf_to_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrecievedmodel',
            name='pdf_to_send',
        ),
    ]
