# Generated by Django 4.2.7 on 2023-12-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0052_remove_paymentrecievedmodel_pdf_to_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecievedmodel',
            name='customer_bill_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
